version: '3.1'
services :
  db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: dev-fca
  admin:
    image: adminer
    environment:
          - ADMINER_DESIGN=pepa-linha
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080